name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote add huggingface https://srv2011:$HF_TOKEN@huggingface.co/spaces/srv2011/srv-timesheet-filler
          git push huggingface main --force
